### ISSUE TITLE
建立 models

### ISSUE THREAD

**Issue by Bosh-Kuo** [Bosh-Kuo/Database-2022-Fall#1]
# Context

- 建立 app 
- 根據 proposal 建立各 Table 的 model
- 寫 admin.py 讓後台可以操作透過 model 操作 DB

# Todo

- [x] models.py 新增各 model class
- [x] 測試 makemigration, migrate 是否有問題
- [x] admin.py register 寫好的 model
- [x] 測試 localhost:8000/admin 呢以正長操做各 model
