### ISSUE TITLE
Login Page 功能 & Register 功能

### ISSUE THREAD

**Issue by Bosh-Kuo** [Bosh-Kuo/Database-2022-Fall#18]
# Context

- 使用者可以透過前端登入、註冊、登出
- 登入後將從後端取得的 User 基本資訊存在前端的 global state 中
- 登出後清空該 user 的 global state 

# Todo

- [x] 後端新增 LogInAPI
- [x] 後端新增 RegisterAPI
- [x] 後端新增 LogoutAPI
- [x] 前端新增 login event handler 
- [x] 前端新增 register event handler 
- [x] 前端新增 logout event handler 
- [x] 前端新增 user profile global state
