### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Bosh-Kuo** [Bosh-Kuo/Database-2022-Fall#3]
# Todo

### 前端純畫面(先不管後端)
- [x] #38
- [x] Home Page 畫面
- [x] Product Page 畫面
- [x] Cart Page 畫面
- [x] Wishlist Page 畫面
- [x] Transaction Page 畫面
- [x] User Page 畫面
- [x] Login Page 畫面
- [x] Register Page 畫面

#### 不分頁功能
- [x] User 登入 & 登出
- [x] Search 輸入特定product name 導到特定 product page
#### Home Page 功能
- [x] 顯示所有商品狀態為 on sale 的 product card (sold product 不顯示)
- [x] 根據 category & tag filter 頁面中的 product card
- [x] product card 點選愛心將該商品加入 user 的 wishlist
- [x] product card 點選購物車將該商品加入 user 的 cart
#### Product Page 功能
- [x] 顯示該商品資訊、comment
- [x] Add comment 功能
#### Cart Page 功能
- [x] 顯示欲購 product 清單 (sold product 不顯示)
- [x] 點選 Deal 改變 product status 為 Sold 並將 product 加入 Transaction 的清單中，並且移除 Cart page 中 該 product 資料
- [x] 點選 Remove 將該 product 從 Cart 移除
#### Wishlist Page 功能
- [x] 顯示所有喜歡的 product (sold product 不顯示)
- [x] 點選 Add to cart 將該 product 加入 Cart
- [x] 點選 Remove 將該 product 從 Wishlist 移除
#### Transaction Page 功能
- [x] 顯示該 User 所有已賣出商品的 Table
- [x] 顯示該 User 所有已買入商品的 Table
#### User Page 功能
- [x] 顯示該 User 個人資訊
- [x] 顯示該 User 所有狀態為 on sale 的 product 
- [x] 點選 remove 刪除該 product 資料
#### Login Page 功能
- [x] 輸入使用者名稱、密碼
- [x] 登入成功跳轉頁面到 Home Page
- [x] 登入失敗顯示警告
#### Register Page功能
- [x] 輸入使用者名稱、密碼、email
- [x] 註冊成功跳轉頁面到 Login Page
- [x] 註冊失敗顯示警告
