### ISSUE TITLE
Layout (Navbar) + 配置 Router

### ISSUE THREAD

**Issue by Bosh-Kuo** [Bosh-Kuo/Database-2022-Fall#4]
# Context

### 前端純畫面(先不管後端)
- Layout (Navbar) 
- 配置 Router

# Todo

- [x] 安裝 material ui
- [x] 安裝 react-router-dom
- [x] layout 用material ui 切版
- [x] 點擊按鍵可導向不同 url & component
- [x] search bar 可輸入與按下 enter 可觸發 callback function
- [x] 整理資料夾結構
